### ISSUE TITLE
needs some updates, does not run with latest LTS ASP core 3.1

### ISSUE THREAD

**Issue by papyr** [surveyjs/surveyjs-aspnet-mvc#2]
Hello, I was unable to build and run, I did 80% but some items were still not clear.

Also what is the licensing on this. 

The ASP side doesnt not have clear survey model, can I suggest/paste a nice survey model contribution to the DAL layer.

- [ ] BTW - visual studio has full features free https://visualstudio.microsoft.com/downloads/ choose community
- [ ] I used these steps to migrate to [ASP Core 3.1 LTS](https://www.hanselman.com/blog/UpdatingAnASPNETCore22WebSiteToNETCore31LTS.aspx)

Its much faster and also runs on Linux/Ubuntu etc.

thanks

**Comment by tsv2013** [comment]
Yes, we need to migrate to .Net Core 3.1. We'll add this task in our plans.

At this moment this repo is licensed onder the Attribution-NonCommercial 3.0 Unported (CC BY-NC 3.0) - https://creativecommons.org/licenses/by-nc/3.0/legalcode, explained here - https://creativecommons.org/licenses/by-nc/3.0/

This repo is not a commercial project or a complete production-ready solution. It demonstrates how SurveyJS libraries can be in integrated with the .Net Core backend. I'm not sure it need extra complexity in this sample.

Could you clarify - what do you mean under the "clear survey model"? And what tasks it will solve?

**Comment by papyr** [comment]
Hello, a model is essentially your tables and their relationships in the Database. 

For anyone to effectively use it in their application, they need to _integrate_ both the frontend and the backend where data is stored. The current solution does not show that Data Model or Table structure. In our application we need to be able to link surveys, and some survey components, like specific questions, responses to different groups or vendors. We can do that but only if there is some form of an underlying database structure

**Comment by tsv2013** [comment]
You can create the data model in your application according your needs. this sample is a bolierplate and should be clear enough.

**Comment by tsv2013** [comment]
I've updated this project to the LTS ASP core 3.1.7

**Comment by papyr** [comment]
Thanks 👍
