### ISSUE TITLE
It doesn't work anymore !!!

### ISSUE THREAD

**Issue by BabuBahir** [surveyjs/surveyjs-aspnet-mvc#3]
Try running the latest build . 
Create a matrix Dropdown in surveyjs Creator.  Neither it works in the survey creator nor viewer...

:'(

**Comment by dmitrykurmanov** [comment]
Our [demo ](https://surveyjs-aspnet-mvc.azurewebsites.net/) looks ok for me.
Could you please describe how to reproduce the problem in greater detail?

**Comment by BabuBahir** [comment]
Yeah sure .

1 Git clone this project & run .
2. Go to survey creator .
3.  Drag drop (Matrix)MultipleChoice ...
It doesn't work.....


let me know .. i would record a video if is still unproduced at your end ?

**Comment by BabuBahir** [comment]
This is what it looks like on the creator 

![image](https://user-images.githubusercontent.com/22672829/121805197-c690ac80-cc67-11eb-800b-9c016fb4614e.png)

**Comment by BabuBahir** [comment]
and this is what it looks like on the viewer 

![image](https://user-images.githubusercontent.com/22672829/121805234-f9d33b80-cc67-11eb-95ce-0556817ba035.png)
drop down missing

**Comment by dmitrykurmanov** [comment]
Thanks for the explanation. I'll check it.

**Comment by BabuBahir** [comment]
Hi dmitry...


I was able to correct this issue by adding the following CDN both in the creator & viewer 


[](<script src="https://unpkg.com/knockout@3.5.1/build/output/knockout-latest.js"></script>)

**Comment by dmitrykurmanov** [comment]
@BabuBahir cool. If you have any additional questions feel free to reopen the issue.

**Comment by BabuBahir** [comment]
Hi dmitry...

I was able to fix the creator & view issue by adding the below CDN 

  **<script src="https://unpkg.com/knockout@3.5.1/build/output/knockout-latest.js"></script>**
