### ISSUE TITLE
save surveys

### ISSUE THREAD

**Issue by mehrandinio** [surveyjs/surveyjs-aspnet-mvc#4]
when browser is closed survey remove.why?how can i save surveys?

**Comment by tsv2013** [comment]
Yes, this demo project illustrates how to use SurveyJS products in an ASP.NET Core web application. It stores survey JSON and results in the session storage. In the real world application you need to add some other functionality like DB storage, security and so on. This functionality is not related to SurveyJS core and thus not implemented here.

**Comment by mehrandinio** [comment]
may you help me to stores surveys?

**Comment by tsv2013** [comment]
Unfortunately we don't have resources to provide custom programming services
